'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) =>
  {

    await queryInterface.bulkInsert('comunas', [
      { codigo:'COL', nombre:'COLCHAGUA', fk_pais:1, fk_region:15},
      { codigo:'SAN', nombre:'SAN VICENTE', fk_pais:1, fk_region:15},
      { codigo:'SAN', nombre:'SAN VICENTE DE TAGUA TAGUA', fk_pais:1, fk_region:15},
      { codigo:'PER', nombre:'PEREDONES', fk_pais:1, fk_region:15},
      { codigo:'CHÉ', nombre:'CHÉPICA', fk_pais:1, fk_region:15},
      { codigo:'CHI', nombre:'CHIMBARONGO', fk_pais:1, fk_region:15},
      { codigo:'COD', nombre:'CODEGUA', fk_pais:1, fk_region:15},
      { codigo:'COÍ', nombre:'COÍNCO', fk_pais:1, fk_region:15},
      { codigo:'COL', nombre:'COLTAUCO', fk_pais:1, fk_region:15},
      { codigo:'DOÑ', nombre:'DOÑIHUE', fk_pais:1, fk_region:15},
      { codigo:'GRA', nombre:'GRANEROS', fk_pais:1, fk_region:15},
      { codigo:'LA ', nombre:'LA ESTRELLA', fk_pais:1, fk_region:15},
      { codigo:'LAS', nombre:'LAS CABRAS', fk_pais:1, fk_region:15},
      { codigo:'LIT', nombre:'LITUECHE', fk_pais:1, fk_region:15},
      { codigo:'LOL', nombre:'LOLOL', fk_pais:1, fk_region:15},
      { codigo:'MAC', nombre:'MACHALÍ', fk_pais:1, fk_region:15},
      { codigo:'MAL', nombre:'MALLOA', fk_pais:1, fk_region:15},
      { codigo:'MAR', nombre:'MARCHIHUE', fk_pais:1, fk_region:15},
      { codigo:'MOS', nombre:'MOSTAZAL', fk_pais:1, fk_region:15},
      { codigo:'NAN', nombre:'NANCAGUA', fk_pais:1, fk_region:15},
      { codigo:'NAV', nombre:'NAVIDAD', fk_pais:1, fk_region:15},
      { codigo:'OLI', nombre:'OLIVAR', fk_pais:1, fk_region:15},
      { codigo:'PAL', nombre:'PALMILLA', fk_pais:1, fk_region:15},
      { codigo:'PER', nombre:'PERALILLO', fk_pais:1, fk_region:15},
      { codigo:'PEU', nombre:'PEUMO', fk_pais:1, fk_region:15},
      { codigo:'PIC', nombre:'PICHIDEGUA', fk_pais:1, fk_region:15},
      { codigo:'PIC', nombre:'PICHILEMU', fk_pais:1, fk_region:15},
      { codigo:'PLA', nombre:'PLACILLA', fk_pais:1, fk_region:15},
      { codigo:'PUM', nombre:'PUMANQUE', fk_pais:1, fk_region:15},
      { codigo:'QUI', nombre:'QUINTA DE TILCOCO', fk_pais:1, fk_region:15},
      { codigo:'RAN', nombre:'RANCAGUA', fk_pais:1, fk_region:15},
      { codigo:'REN', nombre:'RENGO', fk_pais:1, fk_region:15},
      { codigo:'REQ', nombre:'REQUÍNOA', fk_pais:1, fk_region:15},
      { codigo:'SAN', nombre:'SAN FERNANDO', fk_pais:1, fk_region:15},
      { codigo:'SAN', nombre:'SANTA CRUZ', fk_pais:1, fk_region:15},
      { codigo:'ARI', nombre:'ARICA', fk_pais:1, fk_region:14},
      { codigo:'CAM', nombre:'CAMARONES', fk_pais:1, fk_region:14},
      { codigo:'GEN', nombre:'GENERAL LAGOS', fk_pais:1, fk_region:14},
      { codigo:'PUT', nombre:'PUTRE', fk_pais:1, fk_region:14},
      { codigo:'ALT', nombre:'ALTO HOSPICIO', fk_pais:1, fk_region:13},
      { codigo:'CAM', nombre:'CAMIÑA', fk_pais:1, fk_region:13},
      { codigo:'COL', nombre:'COLCHANE', fk_pais:1, fk_region:13},
      { codigo:'HUA', nombre:'HUARA', fk_pais:1, fk_region:13},
      { codigo:'IQU', nombre:'IQUIQUE', fk_pais:1, fk_region:13},
      { codigo:'PIC', nombre:'PICA', fk_pais:1, fk_region:13},
      { codigo:'POZ', nombre:'POZO ALMONTE', fk_pais:1, fk_region:13},
      { codigo:'MAC', nombre:'MACUL', fk_pais:1, fk_region:12},
      { codigo:'EL ', nombre:'EL BOSQUE', fk_pais:1, fk_region:12},
      { codigo:'MAR', nombre:'MARÍA PINTO', fk_pais:1, fk_region:12},
      { codigo:'PAD', nombre:'PADRE HURTADO', fk_pais:1, fk_region:12},
      { codigo:'PAI', nombre:'PAINE', fk_pais:1, fk_region:12},
      { codigo:'PED', nombre:'PEDRO AGUIRRE CERDA', fk_pais:1, fk_region:12},
      { codigo:'PEÑ', nombre:'PEÑAFLOR', fk_pais:1, fk_region:12},
      { codigo:'PRO', nombre:'PROVIDENCIA', fk_pais:1, fk_region:12},
      { codigo:'PUD', nombre:'PUDAHUEL', fk_pais:1, fk_region:12},
      { codigo:'PUE', nombre:'PUENTE ALTO', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN JOSÉ DE MAIPO', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN MIGUEL', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN PEDRO', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN RAMÓN', fk_pais:1, fk_region:12},
      { codigo:'TAL', nombre:'TALAGANTE', fk_pais:1, fk_region:12},
      { codigo:'TIL', nombre:'TILTIL', fk_pais:1, fk_region:12},
      { codigo:'PEÑ', nombre:'PEÑALOLÉN', fk_pais:1, fk_region:12},
      { codigo:'ALH', nombre:'ALHUÉ', fk_pais:1, fk_region:12},
      { codigo:'BUI', nombre:'BUIN', fk_pais:1, fk_region:12},
      { codigo:'CAL', nombre:'CALERA DE TANGO', fk_pais:1, fk_region:12},
      { codigo:'CER', nombre:'CERRILLOS', fk_pais:1, fk_region:12},
      { codigo:'CER', nombre:'CERRO NAVIA', fk_pais:1, fk_region:12},
      { codigo:'COL', nombre:'COLINA', fk_pais:1, fk_region:12},
      { codigo:'CON', nombre:'CONCHALÍ', fk_pais:1, fk_region:12},
      { codigo:'CUR', nombre:'CURACAVÍ', fk_pais:1, fk_region:12},
      { codigo:'EL ', nombre:'EL MONTE', fk_pais:1, fk_region:12},
      { codigo:'EST', nombre:'ESTACIÓN CENTRAL', fk_pais:1, fk_region:12},
      { codigo:'HUE', nombre:'HUECHURABA', fk_pais:1, fk_region:12},
      { codigo:'IND', nombre:'INDEPENDENCIA', fk_pais:1, fk_region:12},
      { codigo:'ISL', nombre:'ISLA DE MAIPO', fk_pais:1, fk_region:12},
      { codigo:'LA ', nombre:'LA CISTERNA', fk_pais:1, fk_region:12},
      { codigo:'LA ', nombre:'LA FLORIDA', fk_pais:1, fk_region:12},
      { codigo:'LA ', nombre:'LA GRANJA', fk_pais:1, fk_region:12},
      { codigo:'LA ', nombre:'LA PINTANA', fk_pais:1, fk_region:12},
      { codigo:'LA ', nombre:'LA REINA', fk_pais:1, fk_region:12},
      { codigo:'LAM', nombre:'LAMPA', fk_pais:1, fk_region:12},
      { codigo:'LAS', nombre:'LAS CONDES', fk_pais:1, fk_region:12},
      { codigo:'LO ', nombre:'LO BARNECHEA', fk_pais:1, fk_region:12},
      { codigo:'LO ', nombre:'LO ESPEJO', fk_pais:1, fk_region:12},
      { codigo:'LO ', nombre:'LO PRADO', fk_pais:1, fk_region:12},
      { codigo:'MAI', nombre:'MAIPÚ', fk_pais:1, fk_region:12},
      { codigo:'MEL', nombre:'MELIPILLA', fk_pais:1, fk_region:12},
      { codigo:'ÑUÑ', nombre:'ÑUÑOA', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SANTIAGO', fk_pais:1, fk_region:12},
      { codigo:'PIR', nombre:'PIRQUE', fk_pais:1, fk_region:12},
      { codigo:'QUI', nombre:'QUILICURA', fk_pais:1, fk_region:12},
      { codigo:'QUI', nombre:'QUINTA NORMAL', fk_pais:1, fk_region:12},
      { codigo:'REC', nombre:'RECOLETA', fk_pais:1, fk_region:12},
      { codigo:'REN', nombre:'RENCA', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN BERNARDO', fk_pais:1, fk_region:12},
      { codigo:'SAN', nombre:'SAN JOAQUÍN', fk_pais:1, fk_region:12},
      { codigo:'VIT', nombre:'VITACURA', fk_pais:1, fk_region:12},
      { codigo:'CAU', nombre:'CAUQUENES', fk_pais:1, fk_region:11},
      { codigo:'CHA', nombre:'CHANCO', fk_pais:1, fk_region:11},
      { codigo:'COL', nombre:'COLBÚN', fk_pais:1, fk_region:11},
      { codigo:'CON', nombre:'CONSTITUCIÓN', fk_pais:1, fk_region:11},
      { codigo:'CUR', nombre:'CUREPTO', fk_pais:1, fk_region:11},
      { codigo:'CUR', nombre:'CURICÓ', fk_pais:1, fk_region:11},
      { codigo:'EMP', nombre:'EMPEDRADO', fk_pais:1, fk_region:11},
      { codigo:'HUA', nombre:'HUALAÑÉ', fk_pais:1, fk_region:11},
      { codigo:'LIC', nombre:'LICANTÉN', fk_pais:1, fk_region:11},
      { codigo:'LIN', nombre:'LINARES', fk_pais:1, fk_region:11},
      { codigo:'LON', nombre:'LONGAVÍ', fk_pais:1, fk_region:11},
      { codigo:'MAU', nombre:'MAULE', fk_pais:1, fk_region:11},
      { codigo:'MOL', nombre:'MOLINA', fk_pais:1, fk_region:11},
      { codigo:'PAR', nombre:'PARRAL', fk_pais:1, fk_region:11},
      { codigo:'PEL', nombre:'PELARCO', fk_pais:1, fk_region:11},
      { codigo:'PEL', nombre:'PELLUHUE', fk_pais:1, fk_region:11},
      { codigo:'PEN', nombre:'PENCAHUE', fk_pais:1, fk_region:11},
      { codigo:'RAU', nombre:'RAUCO', fk_pais:1, fk_region:11},
      { codigo:'RET', nombre:'RETIRO', fk_pais:1, fk_region:11},
      { codigo:'RÍO', nombre:'RÍO CLARO', fk_pais:1, fk_region:11},
      { codigo:'ROM', nombre:'ROMERAL', fk_pais:1, fk_region:11},
      { codigo:'SAG', nombre:'SAGRADA FAMILIA', fk_pais:1, fk_region:11},
      { codigo:'SAN', nombre:'SAN CLEMENTE', fk_pais:1, fk_region:11},
      { codigo:'SAN', nombre:'SAN JAVIER', fk_pais:1, fk_region:11},
      { codigo:'SAN', nombre:'SAN RAFAEL', fk_pais:1, fk_region:11},
      { codigo:'TAL', nombre:'TALCA', fk_pais:1, fk_region:11},
      { codigo:'TEN', nombre:'TENO', fk_pais:1, fk_region:11},
      { codigo:'VIC', nombre:'VICHUQUÉN', fk_pais:1, fk_region:11},
      { codigo:'VIL', nombre:'VILLA ALEGRE', fk_pais:1, fk_region:11},
      { codigo:'YER', nombre:'YERBAS BUENAS', fk_pais:1, fk_region:11},
      { codigo:'PAI', nombre:'PAIHUACO', fk_pais:1, fk_region:10},
      { codigo:'AND', nombre:'ANDACOLLO', fk_pais:1, fk_region:10},
      { codigo:'CAN', nombre:'CANELA', fk_pais:1, fk_region:10},
      { codigo:'COM', nombre:'COMBARBALÁ', fk_pais:1, fk_region:10},
      { codigo:'COQ', nombre:'COQUIMBO', fk_pais:1, fk_region:10},
      { codigo:'ILL', nombre:'ILLAPEL', fk_pais:1, fk_region:10},
      { codigo:'LA ', nombre:'LA HIGUERA', fk_pais:1, fk_region:10},
      { codigo:'LA ', nombre:'LA SERENA', fk_pais:1, fk_region:10},
      { codigo:'LOS', nombre:'LOS VILOS', fk_pais:1, fk_region:10},
      { codigo:'MON', nombre:'MONTE PATRIA', fk_pais:1, fk_region:10},
      { codigo:'OVA', nombre:'OVALLE', fk_pais:1, fk_region:10},
      { codigo:'PUN', nombre:'PUNITAQUI', fk_pais:1, fk_region:10},
      { codigo:'RÍO', nombre:'RÍO HURTADO', fk_pais:1, fk_region:10},
      { codigo:'SAL', nombre:'SALAMANCA', fk_pais:1, fk_region:10},
      { codigo:'VIC', nombre:'VICUÑA', fk_pais:1, fk_region:10},
      { codigo:'ALT', nombre:'ALTO DEL CARMEN', fk_pais:1, fk_region:9},
      { codigo:'CAL', nombre:'CALDERA', fk_pais:1, fk_region:9},
      { codigo:'CHA', nombre:'CHAÑARAL', fk_pais:1, fk_region:9},
      { codigo:'COP', nombre:'COPIAPÓ', fk_pais:1, fk_region:9},
      { codigo:'DIE', nombre:'DIEGO DE ALMAGRO', fk_pais:1, fk_region:9},
      { codigo:'FRE', nombre:'FREIRINA', fk_pais:1, fk_region:9},
      { codigo:'HUA', nombre:'HUASCO', fk_pais:1, fk_region:9},
      { codigo:'TIE', nombre:'TIERRA AMARILLA', fk_pais:1, fk_region:9},
      { codigo:'VAL', nombre:'VALLENAR', fk_pais:1, fk_region:9},
      { codigo:'ÑIQ', nombre:'ÑIQUEN', fk_pais:1, fk_region:8},
      { codigo:'ALT', nombre:'ALTO BIOBÍO', fk_pais:1, fk_region:8},
      { codigo:'ANT', nombre:'ANTUCO', fk_pais:1, fk_region:8},
      { codigo:'ARA', nombre:'ARAUCO', fk_pais:1, fk_region:8},
      { codigo:'BUL', nombre:'BULNES', fk_pais:1, fk_region:8},
      { codigo:'CAB', nombre:'CABRERO', fk_pais:1, fk_region:8},
      { codigo:'CAÑ', nombre:'CAÑETE', fk_pais:1, fk_region:8},
      { codigo:'CHI', nombre:'CHIGUAYANTE', fk_pais:1, fk_region:8},
      { codigo:'CHI', nombre:'CHILLÁN', fk_pais:1, fk_region:8},
      { codigo:'CHI', nombre:'CHILLÁN VIEJO', fk_pais:1, fk_region:8},
      { codigo:'COB', nombre:'COBQUECURA', fk_pais:1, fk_region:8},
      { codigo:'COE', nombre:'COELEMU', fk_pais:1, fk_region:8},
      { codigo:'COI', nombre:'COIHUECO', fk_pais:1, fk_region:8},
      { codigo:'CON', nombre:'CONCEPCIÓN', fk_pais:1, fk_region:8},
      { codigo:'CON', nombre:'CONTULMO', fk_pais:1, fk_region:8},
      { codigo:'COR', nombre:'CORONEL', fk_pais:1, fk_region:8},
      { codigo:'CUR', nombre:'CURANILAHUE', fk_pais:1, fk_region:8},
      { codigo:'EL ', nombre:'EL CARMEN', fk_pais:1, fk_region:8},
      { codigo:'FLO', nombre:'FLORIDA', fk_pais:1, fk_region:8},
      { codigo:'HUA', nombre:'HUALPÉN', fk_pais:1, fk_region:8},
      { codigo:'HUA', nombre:'HUALQUI', fk_pais:1, fk_region:8},
      { codigo:'LAJ', nombre:'LAJA', fk_pais:1, fk_region:8},
      { codigo:'LEB', nombre:'LEBU', fk_pais:1, fk_region:8},
      { codigo:'LOS', nombre:'LOS ÁLAMOS', fk_pais:1, fk_region:8},
      { codigo:'LOS', nombre:'LOS ÁNGELES', fk_pais:1, fk_region:8},
      { codigo:'LOT', nombre:'LOTA', fk_pais:1, fk_region:8},
      { codigo:'MUL', nombre:'MULCHÉN', fk_pais:1, fk_region:8},
      { codigo:'NAC', nombre:'NACIMIENTO', fk_pais:1, fk_region:8},
      { codigo:'NEG', nombre:'NEGRETE', fk_pais:1, fk_region:8},
      { codigo:'NIN', nombre:'NINHUE', fk_pais:1, fk_region:8},
      { codigo:'PEM', nombre:'PEMUCO', fk_pais:1, fk_region:8},
      { codigo:'PEN', nombre:'PENCO', fk_pais:1, fk_region:8},
      { codigo:'PIN', nombre:'PINTO', fk_pais:1, fk_region:8},
      { codigo:'POR', nombre:'PORTEZUELO', fk_pais:1, fk_region:8},
      { codigo:'QUI', nombre:'QUILACO', fk_pais:1, fk_region:8},
      { codigo:'QUI', nombre:'QUILLECO', fk_pais:1, fk_region:8},
      { codigo:'QUI', nombre:'QUILLÓN', fk_pais:1, fk_region:8},
      { codigo:'QUI', nombre:'QUIRIHUE', fk_pais:1, fk_region:8},
      { codigo:'RÁN', nombre:'RÁNQUIL', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN CARLOS', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN FABIÁN', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN IGNACIO', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN NICOLÁS', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN PEDRO DE LA PAZ', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SAN ROSENDO', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SANTA BÁRBARA', fk_pais:1, fk_region:8},
      { codigo:'SAN', nombre:'SANTA JUANA', fk_pais:1, fk_region:8},
      { codigo:'TAL', nombre:'TALCAHUANO', fk_pais:1, fk_region:8},
      { codigo:'TIR', nombre:'TIRÚA', fk_pais:1, fk_region:8},
      { codigo:'TOM', nombre:'TOMÉ', fk_pais:1, fk_region:8},
      { codigo:'TRE', nombre:'TREGUACO', fk_pais:1, fk_region:8},
      { codigo:'TUC', nombre:'TUCAPEL', fk_pais:1, fk_region:8},
      { codigo:'YUM', nombre:'YUMBEL', fk_pais:1, fk_region:8},
      { codigo:'YUN', nombre:'YUNGAY', fk_pais:1, fk_region:8},
      { codigo:'AYS', nombre:'AYSÉN', fk_pais:1, fk_region:7},
      { codigo:'CHI', nombre:'CHILE CHICO', fk_pais:1, fk_region:7},
      { codigo:'CIS', nombre:'CISNES', fk_pais:1, fk_region:7},
      { codigo:'COC', nombre:'COCHRANE', fk_pais:1, fk_region:7},
      { codigo:'COI', nombre:'COIHAIQUE', fk_pais:1, fk_region:7},
      { codigo:'COY', nombre:'COYHAIQUE', fk_pais:1, fk_region:7},
      { codigo:'GUA', nombre:'GUAITECAS', fk_pais:1, fk_region:7},
      { codigo:'LAG', nombre:'LAGO VERDE', fk_pais:1, fk_region:7},
      { codigo:'OHI', nombre:'OHIGGINS', fk_pais:1, fk_region:7},
      { codigo:'RÍO', nombre:'RÍO IBÁÑEZ', fk_pais:1, fk_region:7},
      { codigo:'TOR', nombre:'TORTEL', fk_pais:1, fk_region:7},
      { codigo:'ANT', nombre:'ANTÁRTICA', fk_pais:1, fk_region:6},
      { codigo:'CAB', nombre:'CABO DE HORNOS', fk_pais:1, fk_region:6},
      { codigo:'LAG', nombre:'LAGUNA BLANCA', fk_pais:1, fk_region:6},
      { codigo:'NAT', nombre:'NATALES', fk_pais:1, fk_region:6},
      { codigo:'POR', nombre:'PORVENIR', fk_pais:1, fk_region:6},
      { codigo:'PRI', nombre:'PRIMAVERA', fk_pais:1, fk_region:6},
      { codigo:'PUN', nombre:'PUNTA ARENAS', fk_pais:1, fk_region:6},
      { codigo:'RÍO', nombre:'RÍO VERDE', fk_pais:1, fk_region:6},
      { codigo:'SAN', nombre:'SAN GREGORIO', fk_pais:1, fk_region:6},
      { codigo:'TIM', nombre:'TIMAUKEL', fk_pais:1, fk_region:6},
      { codigo:'TOR', nombre:'TORRES DEL PAINE', fk_pais:1, fk_region:6},
      { codigo:'ANC', nombre:'ANCUD', fk_pais:1, fk_region:5},
      { codigo:'CAL', nombre:'CALBUCO', fk_pais:1, fk_region:5},
      { codigo:'CAS', nombre:'CASTRO', fk_pais:1, fk_region:5},
      { codigo:'CHA', nombre:'CHAITÉN', fk_pais:1, fk_region:5},
      { codigo:'CHO', nombre:'CHONCHI', fk_pais:1, fk_region:5},
      { codigo:'COC', nombre:'COCHAMÓ', fk_pais:1, fk_region:5},
      { codigo:'CUR', nombre:'CURACO DE VÉLEZ', fk_pais:1, fk_region:5},
      { codigo:'DAL', nombre:'DALCAHUE', fk_pais:1, fk_region:5},
      { codigo:'FRE', nombre:'FRESIA', fk_pais:1, fk_region:5},
      { codigo:'FRU', nombre:'FRUTILLAR', fk_pais:1, fk_region:5},
      { codigo:'FUT', nombre:'FUTALEUFÚ', fk_pais:1, fk_region:5},
      { codigo:'HUA', nombre:'HUALAIHUÉ', fk_pais:1, fk_region:5},
      { codigo:'LLA', nombre:'LLANQUIHUE', fk_pais:1, fk_region:5},
      { codigo:'LOS', nombre:'LOS MUERMOS', fk_pais:1, fk_region:5},
      { codigo:'MAU', nombre:'MAULLÍN', fk_pais:1, fk_region:5},
      { codigo:'OSO', nombre:'OSORNO', fk_pais:1, fk_region:5},
      { codigo:'PAL', nombre:'PALENA', fk_pais:1, fk_region:5},
      { codigo:'PUE', nombre:'PUERO OCTAY', fk_pais:1, fk_region:5},
      { codigo:'PUE', nombre:'PUERTO MONTT', fk_pais:1, fk_region:5},
      { codigo:'PUE', nombre:'PUERTO VARAS', fk_pais:1, fk_region:5},
      { codigo:'PUQ', nombre:'PUQUELDÓN', fk_pais:1, fk_region:5},
      { codigo:'PUR', nombre:'PURRANQUE', fk_pais:1, fk_region:5},
      { codigo:'PUY', nombre:'PUYEHUE', fk_pais:1, fk_region:5},
      { codigo:'QUE', nombre:'QUEILÉN', fk_pais:1, fk_region:5},
      { codigo:'QUE', nombre:'QUELLÓN', fk_pais:1, fk_region:5},
      { codigo:'QUE', nombre:'QUEMCHI', fk_pais:1, fk_region:5},
      { codigo:'QUI', nombre:'QUINCHAO', fk_pais:1, fk_region:5},
      { codigo:'RÍO', nombre:'RÍO NEGRO', fk_pais:1, fk_region:5},
      { codigo:'SAN', nombre:'SAN JUAN DE LA COSTA', fk_pais:1, fk_region:5},
      { codigo:'SAN', nombre:'SAN PABLO', fk_pais:1, fk_region:5},
      { codigo:'COR', nombre:'CORRAL', fk_pais:1, fk_region:4},
      { codigo:'FUT', nombre:'FUTRONO', fk_pais:1, fk_region:4},
      { codigo:'LA ', nombre:'LA UNIÓN', fk_pais:1, fk_region:4},
      { codigo:'LAG', nombre:'LAGO RANCO', fk_pais:1, fk_region:4},
      { codigo:'LAN', nombre:'LANCO', fk_pais:1, fk_region:4},
      { codigo:'LOS', nombre:'LOS LAGOS', fk_pais:1, fk_region:4},
      { codigo:'MÁF', nombre:'MÁFIL', fk_pais:1, fk_region:4},
      { codigo:'MAR', nombre:'MARIQUINA', fk_pais:1, fk_region:4},
      { codigo:'PAI', nombre:'PAILLACO', fk_pais:1, fk_region:4},
      { codigo:'PAN', nombre:'PANGUIPULLI', fk_pais:1, fk_region:4},
      { codigo:'RÍO', nombre:'RÍO BUENO', fk_pais:1, fk_region:4},
      { codigo:'VAL', nombre:'VALDIVIA', fk_pais:1, fk_region:4},
      { codigo:'ANG', nombre:'ANGOL', fk_pais:1, fk_region:3},
      { codigo:'CAR', nombre:'CARAHUE', fk_pais:1, fk_region:3},
      { codigo:'CHO', nombre:'CHOLCHOL', fk_pais:1, fk_region:3},
      { codigo:'COL', nombre:'COLLIPULLI', fk_pais:1, fk_region:3},
      { codigo:'CUN', nombre:'CUNCO', fk_pais:1, fk_region:3},
      { codigo:'CUR', nombre:'CURACAUTÍN', fk_pais:1, fk_region:3},
      { codigo:'CUR', nombre:'CURARREHUE', fk_pais:1, fk_region:3},
      { codigo:'ERC', nombre:'ERCILLA', fk_pais:1, fk_region:3},
      { codigo:'FRE', nombre:'FREIRE', fk_pais:1, fk_region:3},
      { codigo:'GAL', nombre:'GALVARINO', fk_pais:1, fk_region:3},
      { codigo:'GOR', nombre:'GORBEA', fk_pais:1, fk_region:3},
      { codigo:'LAU', nombre:'LAUTARO', fk_pais:1, fk_region:3},
      { codigo:'LON', nombre:'LONCOCHE', fk_pais:1, fk_region:3},
      { codigo:'LON', nombre:'LONQUIMAY', fk_pais:1, fk_region:3},
      { codigo:'LOS', nombre:'LOS SAUCES', fk_pais:1, fk_region:3},
      { codigo:'LUM', nombre:'LUMACO', fk_pais:1, fk_region:3},
      { codigo:'MEL', nombre:'MELIPEUCO', fk_pais:1, fk_region:3},
      { codigo:'NUE', nombre:'NUEVA IMPERIAL', fk_pais:1, fk_region:3},
      { codigo:'PAD', nombre:'PADRE LAS CASAS', fk_pais:1, fk_region:3},
      { codigo:'PER', nombre:'PERQUENCO', fk_pais:1, fk_region:3},
      { codigo:'PIT', nombre:'PITRUFQUÉN', fk_pais:1, fk_region:3},
      { codigo:'PUC', nombre:'PUCÓN', fk_pais:1, fk_region:3},
      { codigo:'PUR', nombre:'PURÉN', fk_pais:1, fk_region:3},
      { codigo:'REN', nombre:'RENAICO', fk_pais:1, fk_region:3},
      { codigo:'SAA', nombre:'SAAVEDRA', fk_pais:1, fk_region:3},
      { codigo:'TEM', nombre:'TEMUCO', fk_pais:1, fk_region:3},
      { codigo:'TEO', nombre:'TEODORO SCHMIDT', fk_pais:1, fk_region:3},
      { codigo:'TOL', nombre:'TOLTÉN', fk_pais:1, fk_region:3},
      { codigo:'TRA', nombre:'TRAIGUÉN', fk_pais:1, fk_region:3},
      { codigo:'VIC', nombre:'VICTORIA', fk_pais:1, fk_region:3},
      { codigo:'VIL', nombre:'VILCÚN', fk_pais:1, fk_region:3},
      { codigo:'VIL', nombre:'VILLARRICA', fk_pais:1, fk_region:3},
      { codigo:'LA ', nombre:'LA CALERA', fk_pais:1, fk_region:2},
      { codigo:'ALG', nombre:'ALGARROBO', fk_pais:1, fk_region:2},
      { codigo:'LEY', nombre:'LEYDA-Z', fk_pais:1, fk_region:2},
      { codigo:'CAB', nombre:'CABILDO', fk_pais:1, fk_region:2},
      { codigo:'CAL', nombre:'CALLE LARGA', fk_pais:1, fk_region:2},
      { codigo:'CAR', nombre:'CARTAGENA', fk_pais:1, fk_region:2},
      { codigo:'CAS', nombre:'CASABLANCA', fk_pais:1, fk_region:2},
      { codigo:'CAT', nombre:'CATEMU', fk_pais:1, fk_region:2},
      { codigo:'CON', nombre:'CONCÓN', fk_pais:1, fk_region:2},
      { codigo:'EL ', nombre:'EL QUISCO', fk_pais:1, fk_region:2},
      { codigo:'EL ', nombre:'EL TABO', fk_pais:1, fk_region:2},
      { codigo:'HIJ', nombre:'HIJUELAS', fk_pais:1, fk_region:2},
      { codigo:'ISL', nombre:'ISLA DE PASCUA', fk_pais:1, fk_region:2},
      { codigo:'JUA', nombre:'JUAN FERNÁNDEZ', fk_pais:1, fk_region:2},
      { codigo:'LA ', nombre:'LA CRUZ', fk_pais:1, fk_region:2},
      { codigo:'LA ', nombre:'LA LIGUA', fk_pais:1, fk_region:2},
      { codigo:'LIM', nombre:'LIMACHE', fk_pais:1, fk_region:2},
      { codigo:'LLA', nombre:'LLAILLAY', fk_pais:1, fk_region:2},
      { codigo:'LOS', nombre:'LOS ANDES', fk_pais:1, fk_region:2},
      { codigo:'NOG', nombre:'NOGALES', fk_pais:1, fk_region:2},
      { codigo:'OLM', nombre:'OLMUÉ', fk_pais:1, fk_region:2},
      { codigo:'PAN', nombre:'PANQUEHUE', fk_pais:1, fk_region:2},
      { codigo:'PAP', nombre:'PAPUDO', fk_pais:1, fk_region:2},
      { codigo:'PET', nombre:'PETORCA', fk_pais:1, fk_region:2},
      { codigo:'PUC', nombre:'PUCHUNCAVÍ', fk_pais:1, fk_region:2},
      { codigo:'PUT', nombre:'PUTAENDO', fk_pais:1, fk_region:2},
      { codigo:'QUI', nombre:'QUILLOTA', fk_pais:1, fk_region:2},
      { codigo:'QUI', nombre:'QUILPUÉ', fk_pais:1, fk_region:2},
      { codigo:'QUI', nombre:'QUINTERO', fk_pais:1, fk_region:2},
      { codigo:'RIN', nombre:'RINCONADA', fk_pais:1, fk_region:2},
      { codigo:'SAN', nombre:'SAN ANTONIO', fk_pais:1, fk_region:2},
      { codigo:'SAN', nombre:'SAN ESTEBAN', fk_pais:1, fk_region:2},
      { codigo:'SAN', nombre:'SAN FELIPE', fk_pais:1, fk_region:2},
      { codigo:'SAN', nombre:'SANTA MARÍA', fk_pais:1, fk_region:2},
      { codigo:'SAN', nombre:'SANTO DOMINGO', fk_pais:1, fk_region:2},
      { codigo:'VAL', nombre:'VALPARAÍSO', fk_pais:1, fk_region:2},
      { codigo:'VIL', nombre:'VILLA ALEMANA', fk_pais:1, fk_region:2},
      { codigo:'VIÑ', nombre:'VIÑA DEL MAR', fk_pais:1, fk_region:2},
      { codigo:'ZAP', nombre:'ZAPALLAR', fk_pais:1, fk_region:2},
      { codigo:'ANT', nombre:'ANTOFAGASTA', fk_pais:1, fk_region:1},
      { codigo:'CAL', nombre:'CALAMA', fk_pais:1, fk_region:1},
      { codigo:'MAR', nombre:'MARÍA ELENA', fk_pais:1, fk_region:1},
      { codigo:'MEJ', nombre:'MEJILLONES', fk_pais:1, fk_region:1},
      { codigo:'OLL', nombre:'OLLAGUE', fk_pais:1, fk_region:1},
      { codigo:'SAN', nombre:'SAN PEDRO DE ATACAMA', fk_pais:1, fk_region:1},
      { codigo:'SIE', nombre:'SIERRA GORDA', fk_pais:1, fk_region:1},
      { codigo:'TAL', nombre:'TALTAL', fk_pais:1, fk_region:1},
      { codigo:'TOC', nombre:'TOCOPILLA', fk_pais:1, fk_region:1},

    ], {});

  },

  down: async (queryInterface, Sequelize) =>
  {

     await queryInterface.bulkDelete('comunas', null, {});

  }
};
